export const home_Constants = {
  patientDashboard: {
    headers: [
      {
        headerName: 'Patient Id',
        field: 'patientId',
        sortable: true,
        resizable: true,
      },
      {
        headerName: 'Patient Name',
        field: 'patientName',
        sortable: true,
        resizable: true,
      },
      {
        headerName: 'Gender',
        field: 'gender',
        sortable: true,
        resizable: true,
      },
      { headerName: 'Age', field: 'age', sortable: true, resizable: true },
      {
        headerName: 'Priority',
        field: 'priority',
        sortable: true,
        resizable: true,
      },
      {
        headerName: 'Ref. Doctor',
        field: 'refDoctor',
        sortable: true,
        resizable: true,
      },
      {
        headerName: 'Date & Time',
        field: 'dateTime',
        sortable: true,
        resizable: true,
      },
      {
        headerName: 'Description',
        field: 'description',
        sortable: true,
        resizable: true,
      },
      {
        headerName: 'Report Status',
        field: 'reportStatus',
        sortable: true,
        resizable: true,
      },
      {
        headerName: 'Action',
        field: 'action',
        pinned: 'right',
        width: 120,
        cellRenderer: (data) => {
          return `<mat-icon style="cursor: pointer; margin-top:10px" title="View X-Ray" (click)="viewXray(e)" class="mat-icon material-icons mat-icon-no-color" role="img" aria-hidden="true">
                error_outline</mat-icon>
                <mat-icon style="cursor: pointer; padding-left:15px; margin-top:10px" title="View X-Ray" (click)="viewXray(e)" class="mat-icon material-icons mat-icon-no-color" role="img" aria-hidden="true">
                edit</mat-icon>`;
        },
      },
    ],
    sampleData: [
      {
        patientId: '1',
        patientName: 'Patient1',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'Test1',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '2',
        patientName: 'Patient2',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'Test2',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '3',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '4',
        patientName: 'Patient100',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'Test123',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '5',
        patientName: 'Patient134',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK123',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krishna',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Krish',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
      {
        patientId: '1234',
        patientName: 'Kri',
        gender: 'Male',
        age: '25',
        priority: 'High',
        refDoctor: 'KKK',
        dateTime: 'sdfgsf',
        description: 'efser',
        reportStatus: 'erewrw',
        action: '',
      },
    ],
  },
};
