import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'cxr-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.scss']
})
export class DashboardComponent implements OnInit {

  columnDefs:any;
  rowData: any;
  searchValue: string = '';
  gridApi:any;
  gridColumnApi:any;
  pageSize:any;
  domLayout:any;
  constructor() { }

  ngOnInit(): void {
    this.domLayout = "autoHeight";
    this.rowData = [{patientId: '1234',
                      patientName:'Krishna',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'Krish',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'Kri',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},
                      {patientId: '1234',
                      patientName:'dfds',
                      gender:'Male',
                      age:'25', 
                      priority:'High',
                      refDoctor:'KKK', 
                      dateTime:'sdfgsf', 
                      description:'efser', 
                      reportStatus:'erewrw',
                      action:''},

                    ];
          this.columnDefs = [
            {headerName: 'Patient ID', field: 'patientId', sortable: true, resizable: true },
            {headerName: 'Patient Name', field: 'patientName', sortable: true, resizable: true },
            {headerName: 'Gender', field: 'gender', sortable: true, resizable: true },
            {headerName: 'Age', field: 'age', sortable: true, resizable: true },
            {headerName: 'Priority', field: 'priority', sortable: true, resizable: true },
            {headerName: 'Ref. Doctor', field: 'refDoctor', sortable: true, resizable: true },
            {headerName: 'Date & Time', field: 'dateTime', sortable: true, resizable: true },
            {headerName: 'Description', field: 'description', sortable: true, resizable: true },
            {headerName: 'Report Status', field: 'reportStatus', sortable: true, resizable: true },
            {headerName: 'Action', field: 'action' }
        ];
  }

}
